version: '3.8'
services:
  # server
  server:
    container_name: server
    build:
      context: ./server
    env_file:
      - ./server/.env.prd
    ports:
      - 8000:8000

  #  nginx
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server
    ports:
      - 80:80

