version: '3.8'
services:
  # mysql
  mysql:
    image: mysql:8.0
    container_name: walkdi-database
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: wdpassword
      MYSQL_DATABASE: walkdi
      MYSQL_PASSWORD: wdpassword
