version: '3.8'
services:
  next-app:
    container_name: next-app
    build:
      context: ./client
      dockerfile: Dockerfile

    # Set environment variables directly in the docker-compose file
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - 3000:3000
  app:
    container_name: workspace-server
    build:
      context: ./server
      dockerfile: prd.Dockerfile
    depends_on:
      - mysql
    env_file:
      - .env
    volumes:
      - /usr/src/app/node_modules
    ports:
      - 8000:8000
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - next-app
      - app
    ports:
      - 80:80
  mysql:
    image: mysql:8.0
    container_name: workspace-db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: zhdlsshfoqkd12!ZHDLS
      MYSQL_DATABASE: workspace
      MYSQL_PASSWORD: zhdlsshfoqkd12!ZHDLS
