version: '3.8'
services:
  app:
    container_name: workspace-server
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    depends_on:
      - mysql
    env_file:
      - .env
    volumes:
      - /usr/src/app/node_modules
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    ports:
      - 8000:80
  mysql:
    image: mysql:8.0
    container_name: workspace-db
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: zhdlsshfoqkd12!ZHDLS
      MYSQL_DATABASE: workspace
      MYSQL_PASSWORD: zhdlsshfoqkd12!ZHDLS
