name: Build & Deploy to Digital Ocean

on:
  push:
    branches:
      - test/actions

# env
env:
  IMAGE_NAME: wd-server
  IMAGE_TAG: latest
  DOCKER_REGISTRY: registry.digitalocean.com
  DOCKER_REPOSITORY: walkdi

jobs:
  # build
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Build Nest.js App
        working-directory: ./server
        run: |
          npm install 
          npm run build --if-present

  # deploy
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set NODE_OPTIONS
        run: echo "NODE_OPTIONS='--loader ts-node/esm'" >> $GITHUB_ENV

      - name: Login to Docker Registry
        run: docker login -u ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} -p ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} $DOCKER_REGISTRY

      - name: Build and Push Docker Image
        run: |
          cd ./server
          docker build -t $DOCKER_REGISTRY/$DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG .
          docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG

      - name: SSH into DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_DROPLET_IP }}  
          username: ${{ secrets.DIGITALOCEAN_SSH_USERNAME }}  
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}  
          script: | 
            docker-compose down  
            docker-compose pull
            sudo systemctl stop nginx 
            docker-compose up --build -d  